### ISSUE TITLE
Could not render layout: undefined method `headers' for nil:NilClass  request.headers["Turbo-Frame"]

### ISSUE THREAD

**Issue by seb-sykio** [railsadminteam/rails_admin#3472]
hi
after updating from 3.0.0.beta2 to 3.0.0.rc I have this error:
```

      Failure/Error: xls = ApplicationController.new.render_to_string(filename: filename, template: 'xls', formats: [:xlsx])

NoMethodError:
Could not render layout: undefined method `headers' for nil:NilClass

      request.headers["Turbo-Frame"]
             ^^^^^^^^
# .rvm/gems/ruby-3.1.0/gems/turbo-rails-1.0.1/app/controllers/turbo/frames/frame_request.rb:26:in `turbo_frame_request_id'
# .rvm/gems/ruby-3.1.0/gems/turbo-rails-1.0.1/app/controllers/turbo/frames/frame_request.rb:22:in `turbo_frame_request?'
# .rvm/gems/ruby-3.1.0/gems/turbo-rails-1.0.1/app/controllers/turbo/frames/frame_request.rb:16:in `block (2 levels) in <module:FrameRequest>'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/layouts.rb:327:in `_layout'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/layouts.rb:414:in `_default_layout'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/layouts.rb:390:in `block in _layout_for_option'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/template_renderer.rb:108:in `resolve_layout'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/template_renderer.rb:88:in `find_layout'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/template_renderer.rb:71:in `render_with_layout'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/rendering.rb:117:in `block in _render_template'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/base.rb:270:in `in_rendering_context'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/rendering.rb:116:in `_render_template'
# .rvm/gems/ruby-3.1.0/gems/actionpack-7.0.1/lib/action_controller/metal/streaming.rb:216:in `_render_template'
# .rvm/gems/ruby-3.1.0/gems/actionview-7.0.1/lib/action_view/rendering.rb:103:in `render_to_body'
# .rvm/gems/ruby-3.1.0/gems/actionpack-7.0.1/lib/action_controller/metal/rendering.rb:46:in `render_to_body'
# .rvm/gems/ruby-3.1.0/gems/actionpack-7.0.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
# .rvm/gems/ruby-3.1.0/gems/actionpack-7.0.1/lib/abstract_controller/rendering.rb:47:in `render_to_string'
# .rvm/gems/ruby-3.1.0/gems/actionpack-7.0.1/lib/action_controller/metal/rendering.rb:35:in `render_to_string'
# .rvm/gems/ruby-3.1.0/bundler/gems/wicked_pdf-769f9df487f3/lib/wicked_pdf/pdf_helper.rb:27:in `render_to_string'
# ./app/models/prescriber.rb:386:in `block in generate_xls'
# ./app/models/prescriber.rb:381:in `each'
# ./app/models/prescriber.rb:381:in `generate_xls'
# ./spec/models/prescriber_spec.rb:245:in `block (4 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# NoMethodError:
#   undefined method `headers' for nil:NilClass
#   
#         request.headers["Turbo-Frame"]
#                ^^^^^^^^
#   .rvm/gems/ruby-3.1.0/gems/turbo-rails-1.0.1/app/controllers/turbo/frames/frame_request.rb:26:in `turbo_frame_request_id'


```

**Comment by codealchemy** [comment]
It looks like this is happening (only?) in tests, and may have more to do with how the request is set up in tests (or `wicked_pdf`) than `rails_admin`.

[Related check in `turbo-rails`](https://github.com/hotwired/turbo-rails/blob/48d40d49c26e4be252110eee93597a4a31dbf42a/app/controllers/turbo/frames/frame_request.rb#L21-L27).

**Comment by codealchemy** [comment]
Closing as stale - please re-open and follow the bug report template if you feel this is in error.
