### PR TITLE
fix: update CONTRIBUTING.md documentation for mac setup

### PR DESCRIPTION
**Pull request by jamesoneill997**
Wanted to get this setup locally on mac and ran into a couple of non-intuitive issues. 

Tested and working on MacOS Sequoia Version 15.6.1.

### CODE REVIEW

**Comment by jamesoneill997** [comment]
I'd imagine that remaining failure is to do with importmap stuff.
```
     Failure/Error: imports['@popperjs/core'].gsub!('lib/index.js', 'dist/esm/popper.js')

     NoMethodError:
       undefined method `gsub!' for nil:NilClass
```

**Comment by mshibuya** [comment]
Merged in. Thank you!
