### ISSUE TITLE
scopes in list view not work with RA 0.6.6

### ISSUE THREAD

**Issue by fmh** [railsadminteam/rails_admin#2143]
undefined method `each' for nil:NilClass
Showing /Users/xxxx/MyHomeCloud/Dev/MyApp/app/views/rails_admin/main/index.html.haml where line 128 raised:

![capture d ecran 2014-12-28 a 21 05 52](https://cloud.githubusercontent.com/assets/56861/5564800/6baccc9e-8ed5-11e4-928d-59db431988b8.png)

**Comment by neyp** [comment]
Any news on this one? Mine doesn't work either with v0.6.5. The scopes array is simply ignored and the tabs just don't show up. I'm using Ruby 2.1.5 and Rails 4.1.8.
